id: "010"
title: "Regular Expression Matching"
difficulty: "Hard"
source: "LeetCode"
tags: "["challenging"]"
source_id: "10"
category: "String"
time_complexity: "O(m*n)"
space_complexity: "O(m*n)"
solved: "false"
