id: "111"
title: "Next Permutation"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "31"
category: "Array"
time_complexity: "O(n)"
space_complexity: "O(1)"
solved: "false"
