# Metadata del problema 1
id: "0001"
title: "Two Sum"
slug: "two-sum"
difficulty: "easy"
source: "LeetCode"
url: "https://leetcode.com/problems/two-sum/"
date_added: "2025-08-14"
tags: ["Array", "Hash Table"]
category: "algorithm"
status: "pending"
attempts: 0
solved: false
notes: ""
time_limit: "1s"
memory_limit: "256MB"
author: "LeetCode"
