id: "105"
title: "Zigzag Conversion"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "6"
category: "String"
time_complexity: "O(n)"
space_complexity: "O(n)"
solved: "false"
