id: "121"
title: "Search in Rotated Sorted Array"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "33"
url: "https://leetcode.com/problems/problem-33/"
