id: "113"
title: "Combination Sum"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "39"
category: "Array"
time_complexity: "O(n^(t/m))"
space_complexity: "O(t/m)"
solved: "false"
