id: "113"
title: "Combination Sum"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "39"
url: "https://leetcode.com/problems/problem-39/"
