# Meta information for LeetCode Problem 115
# Generated automatically by leetcode_scraper.py

# Basic Information (REQUIRED)
id: "224"
title: "Distinct Subsequences"
difficulty: "advanced"

# Problem Classification (REQUIRED)
tags: 
  - "to_categorize"                   # TODO: Update with actual tags after reading problem
  - "leetcode"                        # Platform tag

# Time and Source Information (REQUIRED)
time_minutes: 90        # Estimated solve time for advanced level
source: "leetcode"
problem_id: "115"
url: "https://leetcode.com/problems/problem-115/"

# Contest Information (OPTIONAL - remove if not a contest problem)
# contest_info:
#   type: "weekly"                    # weekly | biweekly | daily
#   number: "XXX"                     # Contest number
#   position: "1"                     # Problem position (1, 2, 3, 4)
#   date: "2025-08-14"            # Contest date

# Problem Characteristics (OPTIONAL)
complexity:
  time: "O(?)"                        # TODO: Update after solving
  space: "O(?)"                       # TODO: Update after solving

# Learning Objectives (OPTIONAL)
learning_objectives:
  - "Practice core algorithm concepts"
  - "Improve problem-solving speed"
  - "Master advanced-level techniques"

# Additional Notes (OPTIONAL)
notes: "Generated by leetcode_scraper.py on 2025-08-14. Please update with actual problem information."

# TODO List for completion:
# 1. Update title with actual problem name
# 2. Replace URL with correct LeetCode problem URL
# 3. Add appropriate tags from the official tag list
# 4. Update time and space complexity after solving
# 5. Remove or complete contest_info section
# 6. Add meaningful learning objectives