id: "108"
title: "Letter Combinations of a Phone Number"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "17"
category: "String"
time_complexity: "O(3^m * 4^n)"
space_complexity: "O(3^m * 4^n)"
solved: "false"
