id: "214"
title: "Candy"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "135"
url: "https://leetcode.com/problems/candy/"
category: "Greedy"
subcategory: "Two-pass Greedy"
time_complexity: "O(n)"
space_complexity: "O(n)"
companies:
  - "Amazon"
  - "Google"
  - "Microsoft"
  - "Apple"
patterns:
  - "Two-pass greedy"
  - "Local constraints"
  - "Minimum satisfying assignment"
similar_problems:
  - "455 # Assign Cookies"
  - "406 # Queue Reconstruction by Height"
  - "134 # Gas Station"
notes: "Two-pass greedy algorithm. Left-to-right then right-to-left to satisfy neighbor constraints."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
