id: "weekly_380_p2"
title: "String Compression II"
difficulty: "Medium"
source: "leetcode"
tags: "["String", "Two Pointers", "Array Manipulation"]"
platform: "leetcode"
contest: "Weekly Contest 380"
problem_number: "2"
points: "4"
time_limit: "1000ms"
memory_limit: "256MB"
constraints:
  - "1 <= chars.length <= 1000"
  - "chars[i] is a lowercase English letter, uppercase English letter, or digit"
approach:
  - "Two pointers technique"
  - "In-place modification"
  - "Character counting and compression"
  - "--"
