id: "weekly_380_p1"
title: "Maximum Frequency"
difficulty: "Easy"
source: "leetcode"
tags: "["Array", "Hash Table", "Frequency Count"]"
platform: "leetcode"
contest: "Weekly Contest 380"
problem_number: "1"
points: "3"
time_limit: "1000ms"
memory_limit: "256MB"
constraints:
  - "1 <= nums.length <= 10^5"
  - "1 <= nums[i] <= 10^5"
approach:
  - "Hash table for frequency counting"
  - "Single pass solution"
  - "O(n) time complexity"
  - "--"
