id: "003"
title: "Longest Substring Without Repeating Characters"
difficulty: "Medium"
source: "LeetCode"
tags: "["string"]"
source_id: "3"
category: "String"
time_complexity: "O(n)"
space_complexity: "O(min(m,n))"
solved: "false"
