id: "011"
title: "Container With Most Water"
difficulty: "Medium"
source: "LeetCode"
tags: "["basic", "beginner-friendly"]"
source_id: "11"
category: "Array"
time_complexity: "O(n)"
space_complexity: "O(1)"
solved: "false"
