id: "204"
title: "Longest Valid Parentheses"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "32"
url: "https://leetcode.com/problems/longest-valid-parentheses/"
category: "Dynamic Programming"
subcategory: "Linear DP"
time_complexity: "O(n)"
space_complexity: "O(n)"
companies:
  - "Microsoft"
  - "Amazon"
  - "Google"
  - "Apple"
patterns:
  - "Stack-based parsing"
  - "1D DP"
  - "Two-pass scanning"
similar_problems:
  - "20  # Valid Parentheses"
  - "22  # Generate Parentheses"
  - "301 # Remove Invalid Parentheses"
notes: "Multiple approaches: DP, stack, two-pass scanning. Each has different space-time tradeoffs."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
