id: "119"
title: "Jump Game"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "55"
category: "Array"
time_complexity: "O(n)"
space_complexity: "O(1)"
solved: "false"
