id: "119"
title: "Jump Game"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "55"
url: "https://leetcode.com/problems/problem-55/"
