# Metadata del problema 5
id: "0005"
title: "Longest Palindromic Substring"
slug: "longest-palindromic-substring"
difficulty: "medium"
source: "LeetCode"
url: "https://leetcode.com/problems/longest-palindromic-substring/"
date_added: "2025-08-14"
tags: ["String", "Dynamic Programming"]
category: "algorithm"
status: "pending"
attempts: 0
solved: false
notes: ""
time_limit: "1s"
memory_limit: "256MB"
author: "LeetCode"
