id: "210"
title: "Word Break II"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "140"
url: "https://leetcode.com/problems/word-break-ii/"
category: "Dynamic Programming"
subcategory: "String DP with Backtracking"
time_complexity: "O(n * 2^n)"
space_complexity: "O(n * 2^n)"
companies:
  - "Amazon"
  - "Google"
  - "Microsoft"
  - "Uber"
patterns:
  - "DP + Backtracking"
  - "Memoization"
  - "String partitioning"
similar_problems:
  - "139 # Word Break"
  - "472 # Concatenated Words"
  - "131 # Palindrome Partitioning"
notes: "Combines DP for feasibility check with backtracking for solution construction. Exponential worst case."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
