id: "209"
title: "Palindrome Partitioning II"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "132"
url: "https://leetcode.com/problems/palindrome-partitioning-ii/"
category: "Dynamic Programming"
subcategory: "String DP"
time_complexity: "O(n²)"
space_complexity: "O(n²)"
companies:
  - "Amazon"
  - "Microsoft"
  - "Google"
  - "Apple"
patterns:
  - "2D DP precomputation"
  - "1D DP optimization"
  - "Palindrome checking"
similar_problems:
  - "131 # Palindrome Partitioning"
  - "5   # Longest Palindromic Substring"
  - "647 # Palindromic Substrings"
notes: "DP with palindrome precomputation. Classic optimization from exponential to polynomial time."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
