id: "001"
title: "Two Sum"
difficulty: "basic"
source: "leetcode"
tags: "["beginner-friendly"]"
time_minutes: "15"
problem_id: "1"
url: "https://leetcode.com/problems/two-sum/"
complexity: ""
time: "O(n)"
space: "O(n)"
learning_objectives:
  - "Practice hashmap for O(1) lookups"
  - "Understand complement search pattern"
  - "Master basic array iteration techniques"
