id: "202"
title: "Regular Expression Matching"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "10"
url: "https://leetcode.com/problems/regular-expression-matching/"
category: "Dynamic Programming"
subcategory: "Pattern Matching"
time_complexity: "O(m*n)"
space_complexity: "O(m*n)"
companies:
  - "Facebook"
  - "Microsoft"
  - "Google"
  - "Uber"
patterns:
  - "2D DP"
  - "Regex matching"
  - "State transitions"
similar_problems:
  - "44  # Wildcard Matching"
  - "72  # Edit Distance"
notes: "Advanced regex matching with . and * operators. Classic DP with complex state transitions."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
