id: "116"
title: "Group Anagrams"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "49"
url: "https://leetcode.com/problems/problem-49/"
