id: "120"
title: "Merge Intervals"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "56"
url: "https://leetcode.com/problems/problem-56/"
