id: "120"
title: "Merge Intervals"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "56"
category: "Array"
time_complexity: "O(n log n)"
space_complexity: "O(log n)"
solved: "false"
