id: "114"
title: "Permutations"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "46"
url: "https://leetcode.com/problems/problem-46/"
