id: "114"
title: "Permutations"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "46"
category: "Array"
time_complexity: "O(sum(P(n,k)))"
space_complexity: "O(n)"
solved: "false"
