id: "201"
title: "Wildcard Matching"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "44"
url: "https://leetcode.com/problems/wildcard-matching/"
category: "Dynamic Programming"
subcategory: "Pattern Matching"
time_complexity: "O(m*n)"
space_complexity: "O(m*n)"
companies:
  - "Google"
  - "Facebook"
  - "Microsoft"
  - "Amazon"
patterns:
  - "2D DP"
  - "Pattern matching"
  - "State reduction"
similar_problems:
  - "10  # Regular Expression Matching"
  - "72  # Edit Distance"
notes: "Classic DP problem with wildcard pattern matching. Can be optimized to O(n) space."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
