id: "125"
title: "Minimum Path Sum"
difficulty: "intermediate"
tags:
time_minutes: 45        # Estimated solve time for intermediate level
source: "leetcode"
problem_id: "64"
url: "https://leetcode.com/problems/problem-64/"
