id: "203"
title: "Edit Distance"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "72"
url: "https://leetcode.com/problems/edit-distance/"
category: "Dynamic Programming"
subcategory: "String DP"
time_complexity: "O(m*n)"
space_complexity: "O(m*n)"
companies:
  - "Google"
  - "Microsoft"
  - "Amazon"
  - "Bloomberg"
patterns:
  - "2D DP"
  - "Levenshtein distance"
  - "String transformation"
similar_problems:
  - "44  # Wildcard Matching"
  - "10  # Regular Expression Matching"
  - "583 # Delete Operation for Two Strings"
notes: "Classic edit distance problem using Wagner-Fischer algorithm. Foundation for many string algorithms."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
