id: "109"
title: "4Sum"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "18"
category: "Array"
time_complexity: "O(n^3)"
space_complexity: "O(1)"
solved: "false"
