id: "212"
title: "Best Time to Buy and Sell Stock III"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "123"
url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/"
category: "Dynamic Programming"
subcategory: "State Machine DP"
time_complexity: "O(n)"
space_complexity: "O(1)"
companies:
  - "Amazon"
  - "Google"
  - "Microsoft"
  - "Apple"
patterns:
  - "State machine DP"
  - "Multiple transactions"
  - "Space optimization"
similar_problems:
  - "121 # Best Time to Buy and Sell Stock"
  - "122 # Best Time to Buy and Sell Stock II"
  - "188 # Best Time to Buy and Sell Stock IV"
notes: "State machine DP with at most 2 transactions. Can be generalized to k transactions."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
