id: "205"
title: "Trapping Rain Water"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "42"
url: "https://leetcode.com/problems/trapping-rain-water/"
category: "Two Pointers"
subcategory: "Array Processing"
time_complexity: "O(n)"
space_complexity: "O(1)"
companies:
  - "Amazon"
  - "Microsoft"
  - "Apple"
  - "Google"
patterns:
  - "Two pointers"
  - "Monotonic stack"
  - "Precomputation"
similar_problems:
  - "11  # Container With Most Water"
  - "84  # Largest Rectangle in Histogram"
  - "407 # Trapping Rain Water II"
notes: "Classic problem with multiple optimal solutions: two pointers, stack, DP preprocessing."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
