id: "104"
title: "Longest Palindromic Substring"
difficulty: "Medium"
source: "LeetCode"
tags: "["intermediate", "algorithms"]"
source_id: "5"
category: "String"
time_complexity: "O(n^2)"
space_complexity: "O(1)"
solved: "false"
