id: "208"
title: "Word Ladder"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "127"
url: "https://leetcode.com/problems/word-ladder/"
category: "Graph"
subcategory: "BFS"
time_complexity: "O(m²*n)"
space_complexity: "O(m²*n)"
companies:
  - "Amazon"
  - "Facebook"
  - "Microsoft"
  - "Google"
patterns:
  - "BFS"
  - "Graph construction"
  - "Level-order traversal"
similar_problems:
  - "126 # Word Ladder II"
  - "433 # Minimum Genetic Mutation"
  - "752 # Open the Lock"
notes: "BFS shortest path in implicit graph. Word transformation with single character changes."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
