id: "207"
title: "Minimum Window Substring"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "76"
url: "https://leetcode.com/problems/minimum-window-substring/"
category: "Sliding Window"
subcategory: "Variable Window"
time_complexity: "O(m+n)"
space_complexity: "O(k)"
companies:
  - "Facebook"
  - "Microsoft"
  - "Amazon"
  - "Google"
patterns:
  - "Sliding window"
  - "Character frequency counting"
  - "Two pointers"
similar_problems:
  - "3   # Longest Substring Without Repeating Characters"
  - "438 # Find All Anagrams in a String"
  - "567 # Permutation in String"
notes: "Advanced sliding window with character frequency constraints. Template for many substring problems."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
