id: "007"
title: "Reverse Integer"
difficulty: "Medium"
source: "LeetCode"
tags: "["basic", "beginner-friendly"]"
source_id: "7"
category: "Math"
time_complexity: "O(log n)"
space_complexity: "O(1)"
solved: "false"
