id: "213"
title: "Binary Tree Maximum Path Sum"
difficulty: "Hard"
source: "custom"
tags: "["tree", "challenging"]"
platform: "LeetCode"
problem_number: "124"
url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/"
category: "Tree"
subcategory: "Tree DP"
time_complexity: "O(n)"
space_complexity: "O(h)"
companies:
  - "Amazon"
  - "Microsoft"
  - "Google"
  - "Facebook"
patterns:
  - "Tree DP"
  - "Post-order traversal"
  - "Global vs local optimization"
similar_problems:
  - "543 # Diameter of Binary Tree"
  - "687 # Longest Univalue Path"
  - "250 # Count Univalue Subtrees"
notes: "Tree DP with global maximum tracking. Careful handling of negative values and path constraints."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
