id: "211"
title: "Maximal Rectangle"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "85"
url: "https://leetcode.com/problems/maximal-rectangle/"
category: "Stack"
subcategory: "Monotonic Stack"
time_complexity: "O(m*n)"
space_complexity: "O(n)"
companies:
  - "Amazon"
  - "Microsoft"
  - "Google"
  - "Facebook"
patterns:
  - "Monotonic stack"
  - "Histogram optimization"
  - "Row-wise processing"
similar_problems:
  - "84  # Largest Rectangle in Histogram"
  - "221 # Maximal Square"
  - "42  # Trapping Rain Water"
notes: "Reduces to largest rectangle in histogram for each row. Classic stack-based optimization."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
