id: "015"
title: "3Sum"
difficulty: "Medium"
source: "LeetCode"
tags: "["basic", "beginner-friendly"]"
source_id: "15"
category: "Array"
time_complexity: "O(n^2)"
space_complexity: "O(1)"
solved: "false"
