id: "012"
title: "Integer to Roman"
difficulty: "Medium"
source: "LeetCode"
tags: "["basic", "beginner-friendly"]"
source_id: "12"
category: "Hash Table"
time_complexity: "O(1)"
space_complexity: "O(1)"
solved: "false"
