id: "008"
title: "String to Integer (atoi)"
difficulty: "Medium"
source: "LeetCode"
tags: "["string"]"
source_id: "8"
category: "String"
time_complexity: "O(n)"
space_complexity: "O(1)"
solved: "false"
