id: "206"
title: "N-Queens"
difficulty: "Hard"
source: "custom"
tags: "["challenging"]"
platform: "LeetCode"
problem_number: "51"
url: "https://leetcode.com/problems/n-queens/"
category: "Backtracking"
subcategory: "Constraint Satisfaction"
time_complexity: "O(n!)"
space_complexity: "O(n²)"
companies:
  - "Microsoft"
  - "Amazon"
  - "Google"
  - "Apple"
patterns:
  - "Backtracking"
  - "Constraint checking"
  - "Board state management"
similar_problems:
  - "52  # N-Queens II"
  - "37  # Sudoku Solver"
  - "79  # Word Search"
notes: "Classic backtracking problem. Optimization with diagonal conflict checking using bit manipulation."
date_added: "2025-08-13"
last_reviewed: "2025-08-13"
status: "active"
