id: "013"
title: "Roman to Integer"
difficulty: "Easy"
source: "LeetCode"
tags: "["beginner-friendly"]"
source_id: "13"
category: "Hash Table"
time_complexity: "O(n)"
space_complexity: "O(1)"
solved: "false"
