id: "014"
title: "Longest Common Prefix"
difficulty: "Easy"
source: "LeetCode"
tags: "["beginner-friendly"]"
source_id: "14"
category: "String"
time_complexity: "O(S)"
space_complexity: "O(1)"
solved: "false"
